import React from 'react';
import { AuthProvider } from '../../lib/AuthProvider';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Taskify',
  description: 'Generated by create next app',
  icons:{
    icon: '/logoo.png'
  }
};
const PlatformLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <AuthProvider>{children}</AuthProvider>
    </div>
  );
};

export default PlatformLayout;
